"""
app/models/support_report.py
------------------------------
ORM model for the `support_reports` table.

Freeform, user-submitted issue/damage reports tied to a booking — distinct
from `DamageReport` (app/models/damage_report.py), which is the structured
pickup/return evidence record (condition photos, video) generated by the
rental lifecycle itself. This one is the "something went wrong, here's a
description and maybe some photos" contact-form-style report a renter can
file from their account at any time, reviewed by staff afterward.
"""

import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import ARRAY, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class SupportReport(Base):
    __tablename__ = "support_reports"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    user_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    booking_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("bookings.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    description: Mapped[str] = mapped_column(Text, nullable=False)
    # Arrays of S3 URLs, same upload pipeline as damage_report images.
    image_urls: Mapped[list] = mapped_column(
        ARRAY(String), nullable=False, server_default="{}"
    )
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="new", server_default="new"
    )
    admin_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ('new', 'reviewed', 'resolved')",
            name="ck_support_report_status",
        ),
    )
